language: go

sudo: false

matrix:
  include:
    - go: "1.11.x"
      env: GO111MODULE=off
    - go: "1.11.x"
      env: GO111MODULE=on
    - go: tip
  script:
    - ./.travis.gofmt.sh
    - go test -v ./...
